# -*- coding: utf-8 -*-
"""projeto-algoritmo-de-auditoria-de-dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gnguDf0gJhKoY0F-u5Rh-P99NkVs8WuC
"""

LIMITE_SEGURANCA = 1000

#função
def analisar_vendas (venda1, venda2, venda3):
 media = (venda1 + venda2 + venda3) / 3
 print (f"media = {media:.2f}")

 #Trava de segurança
 global LIMITE_SEGURANCA

 #Condições
 if media > LIMITE_SEGURANCA:
  print("SISTEMA EM QUARENTENA")
 if venda1 > media *5:
  print("REVISÃO MANUAL")
 if venda2 > media *5:
  print("REVISÃO MANUAL")
 if venda3 > media *5:
  print("REVISÃO MANUAL")

 #Conferência de tipo
 print ("tipo da venda 1 ",type(venda1))
 print ("tipo da venda 2 ",type(venda2))
 print ("tipo da venda 3 ",type(venda3))

#Entrada
venda1 = float(input("Venda1 R$ "))
venda2 = float(input("Venda2 R$ "))
venda3 = float(input("Venda3 R$ "))

analisar_vendas(venda1, venda2, venda3)

