# -*- coding: utf-8 -*-
"""matrizes-musicais.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18gGzRyf13q7uZfvlsODMfm45NIk553rh
"""

biblioteca_musical = {

  "Toques": [

    {"Alegre": ([440, 480], [520, 560])},

    {"Triste": ([200, 150], [100, 50])}

  ]

}



for toque in biblioteca_musical["Toques"]:



  for nome_melodia, matriz in toque.items():



    linha1 = matriz[0]

    linha2 = matriz[1]



    matriz_transposta = (

      [linha1[0], linha2[0]],

      [linha1[1], linha2[1]]

    )



    toque.update({nome_melodia: matriz_transposta})



print("Biblioteca Musical Transposta:")

for t in biblioteca_musical["Toques"]:

  print(t)