# -*- coding: utf-8 -*-
"""o-criador-de-emojis-pixels-rgb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JgC3kIn4AfZku4NpAUP4EWE4iBMKRXya
"""

import matplotlib.pyplot as plt



emoji_data = {

  "nome": "Smile",

  "grade": [

    [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)], #

    [(255,255,0), (0,0,0),   (255,255,0), (0,0,0),   (255,255,0)], #

    [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)], #

    [(255,255,0), (0,0,0),   (0,0,0),   (0,0,0),   (255,255,0)], #

    [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)] #

  ]

}



for chave, valor in emoji_data.items():

  if chave == "grade":

    nova_grade = []



    for linha in valor:

      nova_linha = []



      for pixel in linha:



        if pixel == (255, 255, 0):

          r, g, b = pixel

          pixel_sombreado = (int(r / 2), int(g / 2), int(b / 2))

          nova_linha.append(pixel_sombreado)

        else:

          nova_linha.append(pixel)



      nova_grade.append(nova_linha)



emoji_data["grade"] = nova_grade

print(f"Emoji: {emoji_data['nome']}")

print(f"Cor do fundo processada: {emoji_data['grade'][0][0]}")



plt.imshow(emoji_data["grade"])

plt.show()