# -*- coding: utf-8 -*-
"""o-integrador.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AgiG8U4dDsUxzrUWRmzgObbZDJ2vECUK
"""

galeria_de_arte = {

  "fotos": [



    [[(255, 0, 0), (255, 0, 0), (255, 0, 0)],

     [(255, 0, 0), (255, 0, 0), (255, 0, 0)],

     [(255, 0, 0), (255, 0, 0), (255, 0, 0)]],





    [[(0, 0, 255), (0, 0, 255), (0, 0, 255)],

     [(0, 0, 255), (0, 0, 255), (0, 0, 255)],

     [(0, 0, 255), (0, 0, 255), (0, 0, 255)]]

  ]

}





for categoria in galeria_de_arte.keys():

  lista_imagens = galeria_de_arte[categoria]





  for i in range(len(lista_imagens)):

    imagem_atual = lista_imagens[i]

    print(f"Processando imagem {i+1} da categoria '{categoria}'...")





    for linha in imagem_atual:



      if len(linha) > 0:

        pixel_descartado = linha.pop()





      novo_pixel_borda = (128, 128, 128)

      linha.insert(0, novo_pixel_borda)



print("\nProcessamento concluído com sucesso!")

print(f"Exemplo da primeira linha alterada: {galeria_de_arte['fotos'][0][0]}")