# -*- coding: utf-8 -*-
"""navegação-e-evacuação-espacial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YJ17rlqPtTwuL06Cs1n1tE8iHndKuFbu
"""

def simulador_evacuacao():

  locais = ["Quarto (mais distante)", "Corredor 1", "Sala de Estar", "Cozinha", "Hall de Entrada", "Saída Principal"]

  estados = ["caminho livre", "porta aberta", "extintor disponível", "chave disponível", "porta trancada", "caminho livre"]



  inventario = []

  posicao = 0

  energia = 50

  print("=== SIMULADOR DE EVACUAÇÃO - AGENTE CEGO (casa em Vila Carrão) ===\n")



  while posicao < len(locais) - 1 and energia > 0:

    atual = locais[posicao]

    obstaculo = estados[posicao]

    print(f"Agente em: {atual} | Estado: {obstaculo} | Energia: {energia} | Inventário: {inventario}")



    if "porta trancada" in obstaculo:

      if "chave" in inventario:

        print(" → Porta aberta com a chave! Avançando.")

        posicao += 1

        energia -= 3

      else:

        print(" → Sem chave! Retrocedendo para nó anterior...")

        posicao = max(0, posicao - 1)

        energia -= 10

    elif "extintor disponível" in obstaculo or "chave disponível" in obstaculo:

      item = "extintor" if "extintor disponível" in obstaculo else "chave"

      inventario.append(item)

      print(f" → {item.capitalize()} coletado! Avançando.")

      posicao += 1

      energia -= 2

    else:

      print(" → Caminho livre. Avançando.")

      posicao += 1

      energia -= 5



    print("-" * 50)



  if posicao >= len(locais) - 1:

    print(f"\n EVACUAÇÃO CONCLUÍDA com sucesso! Agente chegou à {locais[-1]}.")

  else:

    print("\n Falha na evacuação: energia esgotada antes da saída.")



if __name__ == "__main__":

  analise_microclima()

  print("=" * 60)

  simulador_evacuacao()