# -*- coding: utf-8 -*-
"""o-algoritmo-do-microclima-local.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bs5fqN-vVj3Y0s9sNpUCc_OHcYhI8ww_
"""

def classificar_iqa(iqa):

  """Classifica o IQA conforme faixas oficiais CETESB"""

  match iqa:
    case _ if iqa <= 50:
      return "Boa"
    case _ if 51 <= iqa <= 100:
      return "Moderada"
    case _ if 101 <= iqa <= 199:
      return "Ruim"
    case _ if 200 <= iqa <= 299:
      return "Muito Ruim"
    case _:
      return "Péssima"

def calcular_nota_conforto(temp, umid, iqa):

  """Fórmula própria de Nota de Conforto Urbano (0-10)"""
  pen_temp = abs(temp - 24) / 5.0
  pen_umid = abs(umid - 60) / 20.0
  pen_iqa = iqa / 100.0
  nota = 10 - (pen_temp + pen_umid + pen_iqa)
  if nota > 10:
    nota = 10
  elif nota < 0:
    nota = 0
  return round(nota, 1)

def analise_microclima():
  dados_locais = [
    ["Praça Vila Carrão - 8h", 21, 80, 42],
    ["Praça Vila Carrão - 14h", 27, 60, 65],
    ["Cruzamento Aricanduva - 8h", 22, 75, 85],
    ["Cruzamento Aricanduva - 14h", 28, 52, 145],
    ["Ponto de Ônibus UNICID - 8h", 20, 82, 48],
    ["Ponto de Ônibus UNICID - 14h", 26, 65, 75],
  ]



  print("=== ANÁLISE DO MICROCLIMA LOCAL (Vila Carrão → Aricanduva → UNICID) ===\n")
  for local in dados_locais:          # 1º for: locais
    nome = local[0]
    print(f"Local: {nome}")

    metricas = ["Temperatura (°C)", "Umidade (%)", "IQA"]
    for i in range(3):            # 2º for aninhado: métricas
      print(f" {metricas[i]}: {local[i+1]}")
    temp = local[1]
    umid = local[2]
    iqa = local[3]

    classificacao = classificar_iqa(iqa)

    nota = calcular_nota_conforto(temp, umid, iqa)
    print(f" Classificação IQA: {classificacao}")
    print(f" Nota de Conforto Urbano: {nota}/10\n")

