# -*- coding: utf-8 -*-
"""Sistema de Auditoria de Recursos Corporativos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pzB1wjbqr5kE7C5wp_ojm1TVnbTyAEN1
"""

import time


# Decorator de auditoria
def auditor(funcao):

    def executar(*valores, **opcoes):

        print("--- INICIANDO AUDITORIA ---")

        inicio = time.time()

        print(f"\nValores recebidos: {valores}")
        print(f"Opções recebidas: {opcoes}\n")

        resultado = funcao(*valores, **opcoes)

        fim = time.time()

        tempo_total = fim - inicio

        print("\n--- AUDITORIA FINALIZADA ---")
        print(f"Tempo de execução: {tempo_total:.6f} segundos")
        print("-----------------------------\n")

        return resultado

    return executar


# Estrutura da empresa
empresa = {

    "Matriz": {

        "TI": {

            "Infraestrutura": 185000,
            "Desenvolvimento": 320000,

            "Seguranca": {

                "Redes": 95000,
                "Monitoramento": 78000
            }
        },

        "RH": {

            "Recrutamento": 45000,
            "Treinamento": 38000
        },

        "Financeiro": {

            "Contabilidade": 110000,
            "Auditoria": 87000
        },

        "Marketing": {

            "Publicidade": 140000,
            "SocialMedia": 65000
        }
    }
}


@auditor
def calcular_orcamento(estrutura, *ignorar, **config):

    taxa_cambio = config.get("taxa_cambio", 1)
    moeda_destino = config.get("moeda_destino", "BRL")

    # Função recursiva
    def somar_orcamento(dados):

        total = 0

        for setor, valor in dados.items():

            # Ignora departamentos
            if setor in ignorar:
                print(f"Departamento ignorado: {setor}")
                continue

            # Continua navegando nos dicionários
            if isinstance(valor, dict):
                total += somar_orcamento(valor)

            else:
                total += valor

        return total

    total_final = somar_orcamento(estrutura)

    total_convertido = total_final * taxa_cambio

    print(f"Moeda de destino: {moeda_destino}")

    return total_convertido


# Execução do programa
orcamento_total = calcular_orcamento(
    empresa,
    "RH",
    moeda_destino="BRL",
    taxa_cambio=5.20
)

print(f"Orçamento total: R$ {orcamento_total:,.2f}")